---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates Security Groups

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  License:
    Description: 'Copyright 2019 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at
      http://aws.amazon.com/asl/
      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: AWS Parameters
      Parameters:
        - ExternalAccessCidr
        - VpcId
    ParameterLabels:
      ExternalAccessCidr:
        default: External Access CIDR Block
      VpcId:
        default: Vpc Id

Parameters:
  ExternalAccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: The CIDR IP range that is permitted to access the instances. Note - a value of 0.0.0.0/0 will allow access from ANY IP address.
    Type: String
    Default: 0.0.0.0/0
  VpcId:
    AllowedPattern: ^(vpc-)([a-f0-9]{8,17})$
    Description: The Vpc Id of an existing Vpc.
    Type: AWS::EC2::VPC::Id

Resources:
  ExternalAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref ExternalAccessCidr
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: !Ref ExternalAccessCidr
      VpcId:
        !Ref VpcId
  ExternalAccessSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !Ref ExternalAccessSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref ExternalAccessSecurityGroup
  FsxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Amazon FSx file system
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 445
          ToPort: 445
          SourceSecurityGroupId: !Ref ExternalAccessSecurityGroup
      VpcId:
        !Ref VpcId
  FsxSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !Ref FsxSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref FsxSecurityGroup

Outputs:
  ExternalAccessSecurityGroup:
    Value: !Ref ExternalAccessSecurityGroup
  FsxSecurityGroup:
    Value: !Ref FsxSecurityGroup
