---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates an Amazon FSx for Windows File Server file system

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)
  License:
    Description: 'Copyright 2019 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at
      http://aws.amazon.com/asl/
      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: File system configuration
      Parameters:
        - FileSystemName
        - StorageCapacity
        - ThroughputCapacity
        - SubnetId
        - SecurityGroupId
        - DirectoryId
        - DailyAutomaticBackupStartTime
        - CopyTagsToBackups
        - AutomaticBackupRetentionDays
        - WeeklyMaintenanceStartTime
    ParameterLabels:
      DirectoryId:
        default: Directory Id
      AutomaticBackupRetentionDays:
        default: Backup retention days
      CopyTagsToBackups:
        default: Copy tags to backups
      DailyAutomaticBackupStartTime:
        default: Daily backup start time (optional)
      FileSystemName:
        default: File system name
      SecurityGroupId:
        default: Security group
      StorageCapacity:
        default: Storage capacity (GiB)
      SubnetId:
        default: SubnetId
      ThroughputCapacity:
        default: Throughput capacity (MiB/s)
      WeeklyMaintenanceStartTime:
        default: Weekly maintenance start time (optional)

Parameters:
  DirectoryId:
    AllowedPattern: ^d-[0-9a-f]{10}$
    Description: Active directory id
    Type: String    
  AutomaticBackupRetentionDays:
    Default: 7
    Description: Number of days to retain automatic daily backups (0 to 35 days)
    MaxValue: 35
    MinValue: 0
    Type: Number
  CopyTagsToBackups:
    AllowedValues:
    - '' 
    - true
    - false
    Default: ''
    Description: Stripe set of the files imported from a data repository
    Type: String
  DailyAutomaticBackupStartTime:
    AllowedPattern: ^$|([01]\d|2[0-3]):?([0-5]\d)$
    Description: Enter the daily automatic backup start time in hour:minute UTC format (e.g. 11:30pm = 23:30)
    Type: String
  FileSystemName:
    Default: fsx-windows-workshop
    AllowedPattern: ^$|(.*)$
    Description: Name of file system - name value of key-value pair
    Type: String     
  SecurityGroupId:
    Description: Select an existing security group id
    Type: AWS::EC2::SecurityGroup::Id          
  StorageCapacity:
    Default: 300
    Description: Storage capacity (GiB)
    MaxValue: 64000
    MinValue: 300
    Type: Number
  SubnetId:
    Description: Select an existing subnet id
    Type: AWS::EC2::Subnet::Id
  ThroughputCapacity:
    AllowedValues:
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 2048
    Default: 64
    Description: Throughput capacity (MiB/s)
    Type: String
  WeeklyMaintenanceStartTime:
    AllowedPattern: ^$|[1-7]:([01]\d|2[0-3]):?([0-5]\d)$
    Description: Enter the weekly maintenance start time in day:hour:minute UTC format (e.g. Monday 11:30pm = 1:23:30)
    Type: String

Conditions:
  CopyTagsToBackupsProvided:
    !Not [ !Equals [ '', !Ref CopyTagsToBackups ] ]
  DailyAutomaticBackupStartTimeProvided:
    !Not [ !Equals [ '', !Ref DailyAutomaticBackupStartTime ] ]
  WeeklyMaintenanceStartTimeProvided:
    !Not [ !Equals [ '', !Ref WeeklyMaintenanceStartTime ] ]

Resources:
  WindowsFileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: WINDOWS
      StorageCapacity: !Ref StorageCapacity
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Ref FileSystemName
      WindowsConfiguration:
        ActiveDirectoryId: !Ref DirectoryId
        AutomaticBackupRetentionDays: !Ref AutomaticBackupRetentionDays
        CopyTagsToBackups: !If [ CopyTagsToBackupsProvided, !Ref CopyTagsToBackups, !Ref 'AWS::NoValue' ]
        DailyAutomaticBackupStartTime: !If [ DailyAutomaticBackupStartTimeProvided, !Ref DailyAutomaticBackupStartTime, !Ref 'AWS::NoValue' ]
        ThroughputCapacity: !Ref ThroughputCapacity
        WeeklyMaintenanceStartTime: !If [ WeeklyMaintenanceStartTimeProvided, !Ref WeeklyMaintenanceStartTime, !Ref 'AWS::NoValue' ]

Outputs:
  FileSystemId:
    Value: !Ref WindowsFileSystem
